-- Pradinis Atminimas projekto karkasas.
--
-- Produkcinė bazė buvo pradėta prieš sukuriant migracijų istoriją, todėl naujame
-- tuščiame projekte šį failą reikia taikyti vieną kartą prieš `migrations/` failus.
-- Čia sąmoningai nėra demo duomenų, viešų įkėlimų ar pasenusių lentelių.

create table if not exists public.profiliai (
  id text primary key,
  vardas text,
  pavarde text,
  gimimo_data text,
  mirties_data text,
  epitafija text,
  tekstas_200 text,
  story_blocks_json jsonb not null default '[]'::jsonb,
  layout_json jsonb not null default '{}'::jsonb,
  media_json jsonb not null default '[]'::jsonb,
  access_code_hash text,
  access_code_protected boolean
    generated always as (access_code_hash is not null) stored,
  apmoketa boolean not null default false,
  aktyvus boolean default false,
  owner_id uuid default auth.uid(),
  deleted_at timestamptz,
  statusas text not null default 'laukiama'
    check (statusas in ('laukiama', 'patvirtinta', 'apmoketa', 'atlikta', 'atsaukta')),
  created_at timestamptz not null default now()
);

-- Istorinė medijos lentelė paliekama tik senų įrašų suderinamumui. Naujas
-- redaktorius medijos metaduomenis saugo `profiliai.media_json`.
create table if not exists public.medijos (
  id bigint generated by default as identity primary key,
  profilis_id text,
  tipas text,
  url text,
  pavadinimas text,
  eile bigint
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

alter table public.profiliai enable row level security;
alter table public.medijos enable row level security;
alter table public.user_roles enable row level security;

revoke all on table public.profiliai, public.medijos, public.user_roles
  from public, anon, authenticated;
grant select on table public.user_roles to authenticated;

drop policy if exists "User gali matyti savo role" on public.user_roles;
create policy "User gali matyti savo role"
  on public.user_roles for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- Administratoriaus paskyra pirmiausia sukuriama Supabase Auth, tada jos UUID
-- saugiai įrašomas per SQL Editor:
-- insert into public.user_roles (user_id, role)
-- values ('AUTH_USERS_UUID', 'admin')
-- on conflict (user_id) do update set role = excluded.role;

-- Public help chatbot request counters are kept in the non-exposed private schema.
create schema if not exists private;
create table if not exists private.help_chatbot_rate_limits (
  client_hash text not null,
  bucket_start timestamptz not null,
  request_count integer not null default 0 check (request_count >= 0),
  primary key (client_hash, bucket_start)
);
create index if not exists help_chatbot_rate_limits_cleanup_idx
  on private.help_chatbot_rate_limits (bucket_start);
alter table private.help_chatbot_rate_limits enable row level security;
alter table private.help_chatbot_rate_limits force row level security;
revoke all on table private.help_chatbot_rate_limits
  from public, anon, authenticated, service_role;

create or replace function public.consume_help_chatbot_rate_limit(
  p_client_hash text,
  p_limit integer default 30,
  p_window_seconds integer default 600
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_bucket timestamptz;
  next_count integer;
begin
  if p_client_hash is null or p_client_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'help_chatbot_identity_invalid';
  end if;
  if p_limit < 1 or p_limit > 300 or p_window_seconds < 60 or p_window_seconds > 86400 then
    raise exception 'help_chatbot_limit_invalid';
  end if;
  current_bucket := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );
  delete from private.help_chatbot_rate_limits
  where bucket_start < clock_timestamp() - interval '1 day';
  insert into private.help_chatbot_rate_limits as limits (
    client_hash,
    bucket_start,
    request_count
  ) values (p_client_hash, current_bucket, 1)
  on conflict (client_hash, bucket_start)
  do update set request_count = limits.request_count + 1
  returning request_count into next_count;
  if next_count > p_limit then
    raise exception 'help_chatbot_rate_limited';
  end if;
  return next_count;
end;
$$;
revoke all on function public.consume_help_chatbot_rate_limit(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_help_chatbot_rate_limit(text, integer, integer)
  to service_role;
