-- Pradinis Atminimas projekto karkasas.
--
-- Produkcinė bazė buvo pradėta prieš sukuriant migracijų istoriją, todėl naujame
-- tuščiame projekte šį failą reikia taikyti vieną kartą prieš `migrations/` failus.
-- Čia sąmoningai nėra demo duomenų, viešų įkėlimų ar pasenusių lentelių.

create table if not exists public.profiliai (
  id text primary key,
  vardas text,
  pavarde text,
  gimimo_data text,
  mirties_data text,
  epitafija text,
  tekstas_200 text,
  layout_json jsonb not null default '{}'::jsonb,
  media_json jsonb not null default '[]'::jsonb,
  apmoketa boolean not null default false,
  aktyvus boolean default false,
  owner_id uuid default auth.uid(),
  deleted_at timestamptz,
  statusas text not null default 'laukiama'
    check (statusas in ('laukiama', 'patvirtinta', 'apmoketa', 'atlikta', 'atsaukta')),
  created_at timestamptz not null default now()
);

-- Istorinė medijos lentelė paliekama tik senų įrašų suderinamumui. Naujas
-- redaktorius medijos metaduomenis saugo `profiliai.media_json`.
create table if not exists public.medijos (
  id bigint generated by default as identity primary key,
  profilis_id text,
  tipas text,
  url text,
  pavadinimas text,
  eile bigint
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

alter table public.profiliai enable row level security;
alter table public.medijos enable row level security;
alter table public.user_roles enable row level security;

revoke all on table public.profiliai, public.medijos, public.user_roles
  from public, anon, authenticated;
grant select on table public.user_roles to authenticated;

drop policy if exists "User gali matyti savo role" on public.user_roles;
create policy "User gali matyti savo role"
  on public.user_roles for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- Administratoriaus paskyra pirmiausia sukuriama Supabase Auth, tada jos UUID
-- saugiai įrašomas per SQL Editor:
-- insert into public.user_roles (user_id, role)
-- values ('AUTH_USERS_UUID', 'admin')
-- on conflict (user_id) do update set role = excluded.role;
