begin;
set local statement_timeout='15s';
set local request.jwt.claims='{"role":"service_role"}';
do $$
declare actor uuid;
declare fixture uuid;
declare project uuid:=gen_random_uuid();
declare provider_order uuid:=gen_random_uuid();
declare payload jsonb;
declare attempt uuid;
declare claim uuid;
declare denied boolean;
declare result text;
declare req public.paslaugu_uzklausos%rowtype;
declare count_before integer;
begin
  select id into actor from auth.users limit 1;
  insert into public.paslaugu_uzklausos(owner_id,paslaugos,mirusiojo_vardas,kapiniu_pavadinimas,kapo_vieta,
    quote_status,quote_amount_cents,quote_sent_at,quote_expires_at,quote_accepted_at,payment_status,quote_revision)
  values(actor,array['zvakes'],'Modern checkout test','Test cemetery','Test location','accepted',2500,
    now(),now()+interval '2 days',now(),'pending',1) returning id into fixture;
  denied:=false;
  begin perform public.begin_my_paysera_modern_payment(fixture,gen_random_uuid(),project);
    exception when others then denied:=true; end;
  assert denied,'another owner cannot pay';
  update public.paslaugu_uzklausos set quote_status='sent' where id=fixture;
  denied:=false;
  begin perform public.begin_my_paysera_modern_payment(fixture,actor,project);
    exception when others then denied:=true; end;
  assert denied,'quote must be accepted';
  update public.paslaugu_uzklausos set quote_status='accepted',quote_expires_at=now()-interval '1 hour' where id=fixture;
  denied:=false;
  begin perform public.begin_my_paysera_modern_payment(fixture,actor,project);
    exception when others then denied:=true; end;
  assert denied,'quote must not be expired';
  update public.paslaugu_uzklausos set quote_expires_at=now()+interval '2 days' where id=fixture;
  payload:=public.begin_my_paysera_modern_payment(fixture,actor,project);
  attempt:=(payload->'service'->>'payment_attempt_id')::uuid;
  claim:=(payload->>'claim_token')::uuid;
  assert claim is not null and attempt is not null;
  payload:=public.begin_my_paysera_modern_payment(fixture,actor,project);
  assert payload->>'claim_token' is null,'concurrent request must not create another order';
  assert (payload->'service'->>'payment_attempt_id')::uuid=attempt;
  denied:=false;
  begin perform public.fail_paysera_modern_creation(attempt,claim,500);
    exception when others then denied:=true; end;
  assert denied,'ambiguous failures must retain the claim';
  payload:=public.begin_my_paysera_modern_payment(fixture,actor,project);
  assert payload->>'claim_token' is null;
  perform public.fail_paysera_modern_creation(attempt,claim,400);
  select * into req from public.paslaugu_uzklausos where id=fixture;
  assert req.payment_status='failed' and req.payment_create_token is null,'definite rejection must release claim';
  payload:=public.begin_my_paysera_modern_payment(fixture,actor,project);
  assert (payload->'service'->>'payment_attempt_id')::uuid<>attempt,'definitively rejected order can restart';
  attempt:=(payload->'service'->>'payment_attempt_id')::uuid;
  claim:=(payload->>'claim_token')::uuid;
  denied:=false;
  begin perform public.attach_paysera_modern_order(attempt,gen_random_uuid(),provider_order,project,2500,'EUR');
    exception when others then denied:=true; end;
  assert denied,'wrong creation token must fail';
  denied:=false;
  begin perform public.attach_paysera_modern_order(attempt,claim,provider_order,project,2400,'EUR');
    exception when others then denied:=true; end;
  assert denied,'response amount binding required';
  perform public.attach_paysera_modern_order(attempt,claim,provider_order,project,2500,'EUR');
  perform public.fail_paysera_modern_creation(attempt,claim,422);
  payload:=public.begin_my_paysera_modern_payment(fixture,actor,project);
  assert (payload->'service'->>'payment_attempt_id')::uuid=attempt and payload->'service'->>'payment_session_id'=provider_order::text;
  assert payload->>'claim_token' is not null,'link-only retry retains provider order';
  claim:=(payload->>'claim_token')::uuid;
  denied:=false;
  begin perform public.attach_paysera_modern_link(attempt,claim,provider_order,gen_random_uuid(),'https://evil.test/',now()+interval '30 minutes');
    exception when others then denied:=true; end;
  assert denied,'unsafe redirect must fail';
  perform public.attach_paysera_modern_link(attempt,claim,provider_order,gen_random_uuid(),
    'https://api.paysera.com/checkout-payment-link/payment-collection/v1/payment-links/testlink',now()+interval '30 minutes');
  payload:=public.begin_my_paysera_modern_payment(fixture,actor,project);
  assert payload->>'claim_token' is null and payload->'service'->>'payment_checkout_url' is not null;
  result:=public.process_paysera_modern_payment(attempt,provider_order,project,repeat('a',64),'paid',2400,2500,'EUR',false);
  assert result='rejected_quote_or_amount';
  result:=public.process_paysera_modern_payment(attempt,provider_order,project,repeat('b',64),'paid',2500,2500,'USD',false);
  assert result='rejected_quote_or_amount';
  result:=public.process_paysera_modern_payment(attempt,gen_random_uuid(),project,repeat('c',64),'paid',2500,2500,'EUR',false);
  assert result='rejected_quote_or_amount';
  result:=public.process_paysera_modern_payment(attempt,provider_order,gen_random_uuid(),repeat('d',64),'paid',2500,2500,'EUR',false);
  assert result='rejected_quote_or_amount';
  result:=public.process_paysera_modern_payment(attempt,provider_order,project,repeat('e',64),'paid',2500,1500,'EUR',false);
  assert result='recorded','partial funds must not mark paid';
  select * into req from public.paslaugu_uzklausos where id=fixture;
  assert req.payment_status='processing';
  update public.paslaugu_uzklausos set payment_session_expires_at=now()-interval '1 hour' where id=fixture;
  result:=public.process_paysera_modern_payment(attempt,provider_order,project,repeat('f',64),'paid',2500,2500,'EUR',false);
  assert result='accepted','delayed confirmed payment must be accepted';
  select * into req from public.paslaugu_uzklausos where id=fixture;
  assert req.payment_status='paid' and req.paid_at is not null and not req.payment_test;
  select count(*) into count_before from public.service_payment_events where request_id=fixture;
  result:=public.process_paysera_modern_payment(attempt,provider_order,project,repeat('f',64),'paid',2500,2500,'EUR',false);
  assert result='accepted' and count_before=(select count(*) from public.service_payment_events where request_id=fixture);
  result:=public.process_paysera_modern_payment(attempt,provider_order,project,repeat('1',64),'pending_payment',2500,0,'EUR',false);
  select * into req from public.paslaugu_uzklausos where id=fixture;
  assert req.payment_status='paid','late pending event must not undo payment';

  insert into public.paslaugu_uzklausos(owner_id,paslaugos,mirusiojo_vardas,kapiniu_pavadinimas,kapo_vieta,
    quote_status,quote_amount_cents,quote_sent_at,quote_expires_at,payment_status,quote_revision)
  values(actor,array['zvakes'],'Modern sandbox test','Test cemetery','Test location','accepted',2500,
    now(),now()+interval '2 days','pending',1) returning id into fixture;
  payload:=public.begin_my_paysera_modern_payment(fixture,actor,project);
  attempt:=(payload->'service'->>'payment_attempt_id')::uuid;
  claim:=(payload->>'claim_token')::uuid;
  provider_order:=gen_random_uuid();
  perform public.attach_paysera_modern_order(attempt,claim,provider_order,project,2500,'EUR');
  result:=public.process_paysera_modern_payment(attempt,provider_order,project,repeat('2',64),'paid',2500,2500,'EUR',true);
  select * into req from public.paslaugu_uzklausos where id=fixture;
  assert result='recorded' and req.payment_status='cancelled' and req.paid_at is null and req.payment_test;
  assert not has_function_privilege('anon','public.get_paysera_checkout_credentials()','EXECUTE');
  assert not has_function_privilege('authenticated','public.get_paysera_checkout_credentials()','EXECUTE');
  assert not has_function_privilege('anon','private.read_paysera_checkout_credentials()','EXECUTE');
  assert not has_function_privilege('authenticated','private.read_paysera_checkout_credentials()','EXECUTE');
  assert has_function_privilege('service_role','public.get_paysera_checkout_credentials()','EXECUTE');
  assert not has_function_privilege('authenticated','public.begin_my_paysera_modern_payment(uuid,uuid,uuid)','EXECUTE');
  assert not has_function_privilege('anon','public.process_paysera_modern_payment(uuid,uuid,uuid,text,text,integer,integer,text,boolean)','EXECUTE');
  assert not has_function_privilege('authenticated','public.process_paysera_modern_payment(uuid,uuid,uuid,text,text,integer,integer,text,boolean)','EXECUTE');
end;
$$;
select 'Modern checkout database assertions passed; fixtures rolled back' as result;
rollback;
