begin;
set local statement_timeout='20s';
do $$
declare actor uuid;
declare profile text:='payment-test-'||gen_random_uuid();
declare ord public.uzsakymai%rowtype;
declare reused public.uzsakymai%rowtype;
declare project uuid:=gen_random_uuid();
declare provider_order uuid:=gen_random_uuid();
declare info jsonb;
declare attempt uuid;
declare claim uuid;
declare previous_attempt uuid;
declare previous_provider uuid;
declare result text;
declare denied boolean;
declare saved jsonb;
begin
  select id into actor from auth.users limit 1;
  perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',actor)::text,true);
  insert into public.profiliai(id,owner_id,vardas) values(profile,actor,'Payment test');
  ord:=public.create_paid_product_order(profile,actor,'metal','https://example.test/page','https://example.test/qr');
  assert ord.subtotal_cents=5000 and ord.total_cents is null and not ord.apmoketa;
  reused:=public.create_paid_product_order(profile,actor,'metal','https://example.test/page','https://example.test/qr');
  assert reused.id=ord.id,'repeated create order must reuse unpaid order';
  denied:=false;
  begin perform public.create_paid_product_order(profile,gen_random_uuid(),'metal','https://example.test/','https://example.test/');
    exception when others then denied:=true; end;
  assert denied,'other owner cannot create order';
  denied:=false;
  begin perform public.begin_product_paysera_payment(ord.id,actor,project); exception when others then denied:=true; end;
  assert denied,'delivery required';
  perform public.set_my_order_delivery(ord.id,'Omniva','Vilnius','Test locker','Test payer','+37060000000','test@example.invalid');
  select * into ord from public.uzsakymai where id=ord.id;
  assert ord.total_cents=5300 and ord.shipping_cents=300;
  denied:=false;
  begin perform public.begin_product_paysera_payment(ord.id,gen_random_uuid(),project); exception when others then denied:=true; end;
  assert denied,'payment owner binding';
  info:=public.begin_product_paysera_payment(ord.id,actor,project);
  attempt:=(info->'attempt'->>'id')::uuid; claim:=(info->>'claim_token')::uuid;
  assert attempt is not null and claim is not null;
  info:=public.begin_product_paysera_payment(ord.id,actor,project);
  assert (info->'attempt'->>'id')::uuid=attempt and info->>'claim_token' is null,'no duplicate creation claim';
  denied:=false;
  begin perform public.fail_product_paysera_creation(attempt,claim,500); exception when others then denied:=true; end;
  assert denied,'ambiguous failure retains claim';
  denied:=false;
  begin update public.uzsakymai set subtotal_cents=100 where id=ord.id; exception when others then denied:=true; end;
  assert denied,'in-flight amount locked';
  denied:=false;
  begin perform public.set_my_order_delivery(ord.id,'DPD','Kaunas','Other locker','Test payer','+37060000000','test@example.invalid'); exception when others then denied:=true; end;
  assert denied,'in-flight delivery locked';
  perform public.attach_product_paysera_order(attempt,claim,provider_order,5300,'EUR',project);
  perform public.fail_product_paysera_creation(attempt,claim,422);
  info:=public.begin_product_paysera_payment(ord.id,actor,project);
  claim:=(info->>'claim_token')::uuid;
  assert (info->'attempt'->>'provider_order_id')::uuid=provider_order,'retry only missing link';
  denied:=false;
  begin perform public.attach_product_paysera_link(attempt,claim,provider_order,gen_random_uuid(),'https://evil.test',now()+interval '30 minutes'); exception when others then denied:=true; end;
  assert denied,'unsafe redirect rejected';
  perform public.attach_product_paysera_link(attempt,claim,provider_order,gen_random_uuid(),
    'https://api.paysera.com/checkout-payment-link/payment-collection/v1/payment-links/product-test',now()+interval '30 minutes');
  info:=public.begin_product_paysera_payment(ord.id,actor,project);
  assert info->'attempt'->>'checkout_url' is not null and info->>'claim_token' is null,'link reuse';
  result:=public.process_product_paysera_payment(attempt,provider_order,gen_random_uuid(),repeat('a',64),'paid',5300,5300,'EUR',true);
  assert result='rejected_quote_or_amount';
  result:=public.process_product_paysera_payment(attempt,provider_order,project,repeat('b',64),'paid',100,100,'EUR',true);
  assert result='rejected_quote_or_amount';
  result:=public.process_product_paysera_payment(attempt,provider_order,project,repeat('c',64),'paid',5300,5300,'USD',true);
  assert result='rejected_quote_or_amount';
  result:=public.process_product_paysera_payment(attempt,provider_order,project,repeat('d',64),'paid',5300,100,'EUR',true);
  assert result='recorded';
  assert not (select payment_test from public.uzsakymai where id=ord.id),'partial test does not close order';
  result:=public.process_product_paysera_payment(attempt,provider_order,project,repeat('e',64),'paid',5300,5300,'EUR',true);
  assert result='recorded';
  select to_jsonb(o) into saved from public.uzsakymai o where id=ord.id;
  assert saved->>'payment_status'='cancelled' and saved->>'payment_test'='true' and saved->>'apmoketa'='false';
  assert not exists(select 1 from public.automation_events where order_id=ord.id and event_type='payment.confirmed'),'test sends no payment confirmation';
  result:=public.process_product_paysera_payment(attempt,provider_order,project,repeat('f',64),'paid',5300,5300,'EUR',true);
  assert result='recorded' and (select to_jsonb(o) from public.uzsakymai o where id=ord.id)=saved,'second sandbox callback harmless';
  previous_attempt:=attempt; previous_provider:=provider_order;
  info:=public.begin_product_paysera_payment(ord.id,actor,project);
  attempt:=(info->'attempt'->>'id')::uuid; claim:=(info->>'claim_token')::uuid; provider_order:=gen_random_uuid();
  assert attempt<>previous_attempt;
  perform public.attach_product_paysera_order(attempt,claim,provider_order,5300,'EUR',project);
  result:=public.process_product_paysera_payment(attempt,provider_order,project,repeat('1',64),'paid',5300,5300,'EUR',false);
  assert result='accepted';
  select to_jsonb(o) into saved from public.uzsakymai o where id=ord.id;
  assert saved->>'apmoketa'='true' and saved->>'payment_test'='false';
  assert (select count(*) from public.automation_events where order_id=ord.id and event_type='payment.confirmed')=1;
  result:=public.process_product_paysera_payment(previous_attempt,previous_provider,project,repeat('2',64),'paid',5300,5300,'EUR',true);
  assert result='recorded' and (select to_jsonb(o) from public.uzsakymai o where id=ord.id)=saved,'old test cannot affect paid order';
  result:=public.process_product_paysera_payment(attempt,provider_order,project,repeat('3',64),'paid',5300,5300,'EUR',false);
  assert result='recorded' and (select to_jsonb(o) from public.uzsakymai o where id=ord.id)=saved,'distinct paid callback idempotent';
  assert (select count(*) from public.automation_events where order_id=ord.id and event_type='payment.confirmed')=1;
  assert not has_table_privilege('authenticated','public.product_payment_attempts','SELECT');
  assert not has_function_privilege('anon','public.begin_product_paysera_payment(uuid,uuid,uuid)','EXECUTE');
  assert not has_function_privilege('authenticated','public.process_product_paysera_payment(uuid,uuid,uuid,text,text,integer,integer,text,boolean)','EXECUTE');
end; $$;
rollback;
select 'Product payment assertions passed; fixtures rolled back' as result;
